name: 'Hello js'
description: 'Greet someone and record the time'
inputs:
  who-to-greet: #id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs: 
  time: #id of output
    description: 'Greeting time'
branding:
  icon: 'smile'
  color: 'purple'
runs:
  using: 'node20'
  main: 'index.js'